##############################################################################
# 内容
##############################################################################

# 链接到显示所有项目概览的页面。
# 这可以是外部链接（例如，指向您的GitHub个人资料）或指向您网站内的另一页。
projects_url: https://github.com/Demian1996

# 设置页面方向为RTL或LTR。默认为LTR。 （如果设置为'rtl'，将加载'vazir'字体。）
direction: ltr
# 配置导航菜单。
# 键值对 'Key: url' 将导致在导航菜单中显示到 'url' 的链接，名称为 'Key'。还可以在 languages/*.yml 中为 'Key' 添加翻译。
nav:
  home: /
  articles: /archives/
  tag: /tags/
  about: /about/
  search: /search/

# 链接到您的社交媒体账户。
# 'icon' 键应与Fontawesome图标名称对应
# （请参阅 https://fontawesome.com/icons?d=gallery&s=brands）；
# 仅'mail'是一个例外。
# 您还可以选择添加 'label' 键以设置链接上的标题属性。
# 'label' 丢失时，将使用 'icon' 值作为标题。
social_links:
  -
    icon: github
    link: https://github.com/Demian1996
  -
    icon: mail
    link: mailto:1303465909@qq.com

# 在主页上显示标签云的概览。
# 选项：https://hexo.io/docs/helpers.html#tagcloud
tags_overview: false

# 在主页上显示最新博客文章的概览。
# 选项：
#   - show_all_posts: 是否显示所有可用的帖子。
#   - post_count: 是否只显示 x 最近的帖子。
#   - sort_updated: 按最后修改日期而不是创建日期排序帖子。
posts_overview:
  show_all_posts: false
  post_count: 5
  sort_updated: false

# 自定义存档视图。
# 选项：
#   - sort_updated: 按最后修改日期而不是创建日期排序帖子。
# 注意：这与分页一起使用时不起作用，因为分页插件将按创建日期对页面进行排序。
archive:
  sort_updated: false

# 自定义文章视图。
# 选项：
#   - show_updated: 显示最后修改日期。
post:
  show_updated: false

# 自定义版权年份
# 注意：如果未提供start_year/end_year，将使用当前年份。
copyright:
  start_year: 2018
  end_year:

# 自定义404页面
# 选项：
#   - enabled: 是否启用404页面（404.html）。
error_404:
  enabled: true
  title: "404 Page Not Found"
  description: "您要查找的页面可能已被删除，更改了其名称，或者暂时不可用。"


##############################################################################
# 外观
##############################################################################

# 自定义标题中的标志（即cactus）。
# 选项：
#   - enabled: 是否显示（true）或隐藏（false）标志。
#   - width: 标志的宽度（以像素为单位）。
#   - height: 标志的高度（以像素为单位）。
#   - url: 标志的位置。
#   - gravatar: 是否使用您的Gravatar作为标志。
#   - grayout: 是否在标志上启用悬停效果。
logo:
  enabled: false
  width: 50
  height: 50
  url: /common/avatar1.jpeg
  gravatar: false
  grayout: false

# 自定义favicon。
# cactus支持三个最重要的图标的有限集：
#   - desktop: 经典的favion.ico文件。
#   - android: 一个192x192的PNG文件。
#   - apple:  一个180x180的PNG文件。
# 这些可以使用 http://realfavicongenerator.net/ 生成。
# 选项：
#   - url: 图标的位置。
#   - gravatar: 是否从您的Gravatar创建favicon。
favicon:
  desktop:
    url: /common/favicon.ico
    gravatar: false
  android:
    url: /images/favicon-192x192.png
    gravatar: false
  apple:
    url: /images/apple-touch-icon.png
    gravatar: false

# 应该用于突出显示代码块的颜色方案。
# 请参阅source/css/_highlight以查看所有可用的颜色方案。
# highlight: rainbow

# 设置颜色方案。
# 可用的颜色方案有'dark'，'light'，'classic'和'white'。
# 或者，将您自己的自定义颜色方案添加到source/css/_colors中。
colorscheme: classic

# 页面的最大宽度，以rem为单位。
page_width: 60


##############################################################################
# 杂项
##############################################################################

# 启用或禁用RSS订阅。
rss: false

# 将您的网页转换为图形对象（请参见http://ogp.me）。
open_graph:
  fb_app_id:
  fb_admins:
  twitter_id:
  google_plus:


##############################################################################
# 插件
##############################################################################

# 启用对Latex的MathJax支持
mathjax:
  enabled: false

# 填写Disqus评论的Shortname以启用Disqus评论。
disqus:
  enabled: false
  shortname: cactus-1

# gitalk
# https://github.com/gitalk/gitalk
gitalk:
  client_id: '2f0bc1a2ca8696aee993'
  client_secret: '07f2f355ff46f318cbf507d18a3579dd450b33ae'
  repo: demian1996.github.io
  owner: demian1996
  admin: demian1996
  language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru
  perPage: 10 # Pagination size, with maximum 100.
  distractionFreeMode: false # Facebook-like distraction free mode.
  pagerDirection: last # Comment sorting direction, available values are last and first.
  createIssueManually: false # Gitalk will create a corresponding github issue for your every single page automatically
  option:

# 填写Utterances数据以启用Utterances评论
utterances:
  enabled: false
  repo: owner/githubrepo
  issue_term: pathname
  label: Comment
  theme: github-dark

# 填写Google Analytics跟踪ID以启用Google Analytics。
google_analytics:
  enabled: false
  id: UA-86660611-1

# 填写Baidu Analytics跟踪ID以启用Baidu Analytics。
baidu_analytics:
  enabled: true
  id: b8cfb9edb93ef89e5dd61b1282dba367

# 填写Cloudflare Analytics跟踪ID以启用Cloudflare Analytics。
cloudflare_analytics:
  enabled: false
  id: 0dabb6e21848405483a237e6a7b6ed04

# 填写Umami Analytics跟踪ID以启用Umami Analytics。
umami_analytics:
  enabled: false
  id: e77e68be-f6e4-4br3-9365-2b76b57cd571
  host: https://analytics.domain.com
  script_name: umami.js

# 如果要使用您的Gravatar作为
# 网站的标志和/或favicon，请填写您的Gravatar电子邮件或哈希值。
# 生成哈希：`$ echo -n "name@email.com" | md5`。
gravatar:
  email: name@email.com
  hash: d41d8cd98f00b204e9800998ecf8427e

# 从CDN加载库和样式而不是依赖本地文件
cdn:
  enable: true
  jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2.0.11/dist/clipboard.min.js
  font_awesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
  justified_gallery_css: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/css/justifiedGallery.min.css
  justified_gallery_js: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/js/jquery.justifiedGallery.min.js
